#!/usr/bin/env bash

set -euo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$TESTS_DIR/test_helper.bash"

SANDBOX_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/cyberpunk-integration-test.XXXXXX")"
trap 'rm -rf "$SANDBOX_ROOT"' EXIT
project="$SANDBOX_ROOT/project"
mkdir -p "$project"
git -C "$project" init -q

run_cli() {
    local target="$1"
    shift
    (cd "$target" && "$CYBERPUNK_BIN" "$@")
}

line_count() {
    local value="$1"
    local path="$2"
    grep -Fxc "$value" "$path" || true
}

write_legacy_config() {
    local destination="$1"
    cat > "$destination" <<'EOF'
version: 1

delivery:
  default: integration-branch
  allow_push: false
  allow_pull_requests: false
  allow_deploy: false

workflow:
  mode: adaptive
  levels: [quick, standard, complex]
  repair_cycles_before_rediagnosis: 2
  unresolved_cycles_before_escalation: 3
  project_workflow_note: preserve-this-workflow-line

git:
  integration_branch: auto
  branch_prefix: cyberpunk/
  worktree_root: .worktrees
  require_worktrees: true
  require_non_overlapping_ownership: true
  allow_internal_commits: true
  merge_worker_branches: true
  allow_protected_branch_merge: false
  cleanup_worktrees_after_integration: true
  cleanup_worker_branches: after-confirmation

memory:
  tracked: [.cyberpunk/project.md, .cyberpunk/memory]
  local: .cyberpunk/runs
  promote_only_validated_lessons: true
  project_memory_note: preserve-this-memory-line

skills:
  core_path: skills/core
  project_path: skills/project
  enabled_project: []

project_owned:
  team_note: preserve-this-project-owned-line
EOF
}

section_text() {
    local config="$1"
    local section="$2"
    awk -v section="$section" '
        $0 == section ":" { printing=1 }
        printing && /^[^[:space:]][^:]*:$/ && $0 != section ":" { exit }
        printing { print }
    ' "$config"
}

test_start "fresh project initializes and validates"
assert_exit 0 run_cli "$project" init
assert_exit 0 run_cli "$project" validate
assert_file "$project/AGENTS.md"
assert_file "$project/CLAUDE.md"
assert_file "$project/.cursor/rules/cyberpunk.mdc"
assert_file "$project/.codex/config.toml"
assert_file "$project/.cyberpunk/generated.yml"
assert_file "$project/agents/fixer.md"
assert_file "$project/skills/core/requirements-discovery/SKILL.md"

test_start "existing root instructions and Codex settings coexist with managed adapters"
coexist_project="$SANDBOX_ROOT/coexist"
mkdir -p "$coexist_project/.codex"
printf '%s\n' '# User instructions' > "$coexist_project/AGENTS.md"
printf '%s\n' '# Claude user instructions' > "$coexist_project/CLAUDE.md"
printf '%s\n' '[agents]' 'enabled = false' 'max_concurrent_threads_per_session = 2' > "$coexist_project/.codex/config.toml"
assert_exit 0 run_cli "$coexist_project" init --runtime codex --runtime cursor
assert_contains "$(<"$coexist_project/AGENTS.md")" "# User instructions"
assert_eq 1 "$(line_count '<!-- cyberpunk:start -->' "$coexist_project/AGENTS.md")" "AGENTS start marker count"
assert_eq 1 "$(line_count '<!-- cyberpunk:end -->' "$coexist_project/AGENTS.md")" "AGENTS end marker count"
assert_contains "$(<"$coexist_project/.codex/config.toml")" "enabled = false"
assert_contains "$(<"$coexist_project/.codex/config.toml")" "max_concurrent_threads_per_session = 2"
assert_file "$coexist_project/.cursor/rules/cyberpunk.mdc"
assert_file "$coexist_project/.cyberpunk/generated.yml"
assert_contains "$(<"$coexist_project/.cursor/rules/cyberpunk.mdc")" '<!-- Generated by Cyberpunk. Canonical source is recorded in .cyberpunk/generated.yml. -->'
assert_contains "$(<"$coexist_project/.cyberpunk/generated.yml")" 'path: ".cursor/rules/cyberpunk.mdc"'
assert_contains "$(<"$coexist_project/.cyberpunk/generated.yml")" 'source: ".cyberpunk/workflow.md"'
assert_contains "$(<"$coexist_project/.cyberpunk/generated.yml")" 'runtime: "cursor"'
assert_contains "$(<"$coexist_project/.cyberpunk/generated.yml")" 'kind: "adapter"'
assert_contains "$(<"$coexist_project/.cyberpunk/generated.yml")" 'identifier: "cyberpunk"'
grep -Eq 'sha256: "[0-9a-f]{64}"' "$coexist_project/.cyberpunk/generated.yml" || fail "manifest lacks a SHA-256 record"

test_start "Codex settings are added without replacing unrelated tables"
codex_table_project="$SANDBOX_ROOT/codex-table"
mkdir -p "$codex_table_project/.codex"
printf '%s\n' '[project]' 'name = "sentinel"' > "$codex_table_project/.codex/config.toml"
assert_exit 0 run_cli "$codex_table_project" init --runtime codex
assert_contains "$(<"$codex_table_project/.codex/config.toml")" 'name = "sentinel"'
assert_eq 1 "$(line_count '[agents]' "$codex_table_project/.codex/config.toml")" "appended agents table count"
assert_contains "$(<"$codex_table_project/.codex/config.toml")" "max_concurrent_threads_per_session = 3"

test_start "Codex concurrency is inserted inside an existing agents table"
codex_key_project="$SANDBOX_ROOT/codex-key"
mkdir -p "$codex_key_project/.codex"
printf '%s\n' '[agents]' 'enabled = true' 'default_model = "user-model"' 'reasoning_effort = "high"' '' '[features]' 'shell_tool = true' > "$codex_key_project/.codex/config.toml"
assert_exit 0 run_cli "$codex_key_project" init --runtime codex
codex_key_content="$(<"$codex_key_project/.codex/config.toml")"
assert_contains "$codex_key_content" 'enabled = true'
assert_contains "$codex_key_content" 'default_model = "user-model"'
assert_contains "$codex_key_content" 'reasoning_effort = "high"'
assert_contains "$codex_key_content" 'shell_tool = true'
agents_key_line="$(grep -n '^max_concurrent_threads_per_session = 3$' "$codex_key_project/.codex/config.toml" | cut -d: -f1)"
features_line="$(grep -n '^\[features\]$' "$codex_key_project/.codex/config.toml" | cut -d: -f1)"
[[ "$agents_key_line" -lt "$features_line" ]] || fail "Codex key was not inserted inside [agents]"

test_start "malformed managed markers refuse synchronization without changing user content"
malformed_project="$SANDBOX_ROOT/malformed"
mkdir -p "$malformed_project"
printf '%s\n' '# Sentinel' '<!-- cyberpunk:start -->' 'old body' '<!-- cyberpunk:start -->' '<!-- cyberpunk:end -->' > "$malformed_project/AGENTS.md"
malformed_before="$(cksum "$malformed_project/AGENTS.md")"
capture run_cli "$malformed_project" init --runtime codex
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "managed markers"
assert_eq "$malformed_before" "$(cksum "$malformed_project/AGENTS.md")" "malformed AGENTS content changed"

test_start "reversed managed markers refuse synchronization without changing user content"
reversed_project="$SANDBOX_ROOT/reversed"
mkdir -p "$reversed_project"
printf '%s\n' '# Sentinel' '<!-- cyberpunk:end -->' 'old body' '<!-- cyberpunk:start -->' > "$reversed_project/AGENTS.md"
reversed_before="$(cksum "$reversed_project/AGENTS.md")"
capture run_cli "$reversed_project" init --runtime codex
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "managed markers"
assert_eq "$reversed_before" "$(cksum "$reversed_project/AGENTS.md")" "reversed AGENTS content changed"

test_start "an unowned Cursor adapter collision is never overwritten"
collision_project="$SANDBOX_ROOT/collision"
mkdir -p "$collision_project/.cursor/rules"
printf '%s\n' 'user-owned-cursor-rule' > "$collision_project/.cursor/rules/cyberpunk.mdc"
collision_before="$(cksum "$collision_project/.cursor/rules/cyberpunk.mdc")"
capture run_cli "$collision_project" init --runtime cursor
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "collision"
assert_eq "$collision_before" "$(cksum "$collision_project/.cursor/rules/cyberpunk.mdc")" "collision was overwritten"
capture run_cli "$collision_project" init --runtime cursor --force
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "collision"
assert_eq "$collision_before" "$(cksum "$collision_project/.cursor/rules/cyberpunk.mdc")" "force overwrote an unowned collision"

test_start "generated Cursor drift is preserved unless force is requested"
cursor_rule="$coexist_project/.cursor/rules/cyberpunk.mdc"
manifest="$coexist_project/.cyberpunk/generated.yml"
mkdir -p "$coexist_project/.cursor/rules"
printf '%s\n' '<!-- Generated by Cyberpunk. Canonical source is recorded in .cyberpunk/generated.yml. -->' 'untouched generated adapter' > "$coexist_project/.cursor/rules/untouched.mdc"
if command -v shasum >/dev/null 2>&1; then
    untouched_hash="$(shasum -a 256 "$coexist_project/.cursor/rules/untouched.mdc" | awk '{ print $1 }')"
else
    untouched_hash="$(sha256sum "$coexist_project/.cursor/rules/untouched.mdc" | awk '{ print $1 }')"
fi
printf '%s\n' \
    '  - path: ".cursor/rules/untouched.mdc"' \
    '    source: ".cyberpunk/workflow.md"' \
    '    runtime: "cursor"' \
    '    kind: "adapter"' \
    '    identifier: "untouched"' \
    "    sha256: \"$untouched_hash\"" >> "$manifest"
assert_exit 0 run_cli "$coexist_project" sync
assert_contains "$(<"$manifest")" 'path: ".cursor/rules/untouched.mdc"' "sync abandoned an untouched ownership record"
printf '%s\n' 'local-cursor-edit' >> "$cursor_rule"
drift_before="$(cksum "$cursor_rule")"
manifest_before_drift="$(cksum "$manifest")"
capture bash -c 'source "$1"; validate_generated_manifest "$2"' _ "$REPO_ROOT/lib/generated-assets.bash" "$manifest"
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "Stale generated asset hash"
capture run_cli "$coexist_project" sync
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "drift"
assert_eq "$drift_before" "$(cksum "$cursor_rule")" "non-force sync changed drifted Cursor rule"
assert_eq "$manifest_before_drift" "$(cksum "$manifest")" "failed sync changed ownership manifest"
assert_exit 0 run_cli "$coexist_project" sync --force
assert_not_contains "$(<"$cursor_rule")" "local-cursor-edit"

test_start "managed roots and ownership manifest are stable across repeated sync"
agents_before_sync="$(cksum "$coexist_project/AGENTS.md")"
claude_before_sync="$(cksum "$coexist_project/CLAUDE.md")"
manifest_before_sync="$(cksum "$manifest")"
assert_exit 0 run_cli "$coexist_project" sync
assert_exit 0 run_cli "$coexist_project" sync
assert_eq "$agents_before_sync" "$(cksum "$coexist_project/AGENTS.md")" "AGENTS managed block was not stable"
assert_eq "$claude_before_sync" "$(cksum "$coexist_project/CLAUDE.md")" "CLAUDE content changed for a disabled runtime"
assert_eq "$manifest_before_sync" "$(cksum "$manifest")" "generated manifest was not stable"

test_start "sync migrates a legacy configuration without changing existing policy"
legacy_project="$SANDBOX_ROOT/legacy"
mkdir -p "$legacy_project/.cyberpunk"
write_legacy_config "$legacy_project/.cyberpunk/config.yml"
legacy_delivery_before="$(section_text "$legacy_project/.cyberpunk/config.yml" delivery)"
legacy_workflow_before="$(section_text "$legacy_project/.cyberpunk/config.yml" workflow)"
legacy_git_before="$(section_text "$legacy_project/.cyberpunk/config.yml" git)"
legacy_memory_before="$(section_text "$legacy_project/.cyberpunk/config.yml" memory)"
legacy_skills_before="$(section_text "$legacy_project/.cyberpunk/config.yml" skills)"
legacy_project_owned_before="$(section_text "$legacy_project/.cyberpunk/config.yml" project_owned)"
assert_exit 0 run_cli "$legacy_project" sync
legacy_config="$legacy_project/.cyberpunk/config.yml"
assert_contains "$(<"$legacy_config")" "version: 2"
for value in "runtimes:" "execution:" "models:"; do
    assert_contains "$(<"$legacy_config")" "$value" "legacy migration"
done
assert_eq "$legacy_delivery_before" "$(section_text "$legacy_config" delivery)" "delivery policy changed during migration"
assert_eq "$legacy_workflow_before" "$(section_text "$legacy_config" workflow)" "workflow policy changed during migration"
assert_eq "$legacy_git_before" "$(section_text "$legacy_config" git)" "git policy changed during migration"
assert_eq "$legacy_memory_before" "$(section_text "$legacy_config" memory)" "memory policy changed during migration"
assert_eq "$legacy_skills_before" "$(section_text "$legacy_config" skills)" "skills policy changed during migration"
assert_eq "$legacy_project_owned_before" "$(section_text "$legacy_config" project_owned)" "project-owned policy changed during migration"
legacy_checksum_before="$(cksum "$legacy_config")"
assert_exit 0 run_cli "$legacy_project" sync
legacy_checksum_after="$(cksum "$legacy_config")"
assert_eq "$legacy_checksum_before" "$legacy_checksum_after" "sync migration was not stable"

test_start "every agent default skill resolves"
for agent_file in "$project"/agents/*.md; do
    [[ "$(basename "$agent_file")" == _* ]] && continue
    while IFS= read -r skill; do
        [[ -n "$skill" ]] || continue
        assert_file "$project/skills/core/$skill/SKILL.md"
    done < <(
        awk '
            /^## Default Skills/ { in_skills=1; next }
            /^## / { in_skills=0 }
            in_skills && /^- `/ {
                value=$0
                sub(/^- `/, "", value)
                sub(/`$/, "", value)
                print value
            }
        ' "$agent_file"
    )
done

test_start "generated Fixer exposes the committed PRD handoff"
fixer_contract="$(<"$project/agents/fixer.md")$(<"$project/skills/core/requirements-discovery/SKILL.md")$(<"$project/.cyberpunk/workflow.md")"
for value in \
    "requirements-discovery" \
    "specs/YYYY-MM-DD-<topic>-prd.md" \
    "current named branch" \
    "discovery_complete: true" \
    "user_authorized_handoff: true"; do
    assert_contains "$fixer_contract" "$value" "generated Fixer handoff"
done

test_start "local run and worktree paths are ignored"
git -C "$project" check-ignore -q .cyberpunk/runs/example
git -C "$project" check-ignore -q .worktrees/example

test_start "force refresh preserves user-owned project skills"
mkdir -p "$project/skills/project/release-policy"
printf '%s\n' "project-owned" > "$project/skills/project/release-policy/SKILL.md"
before_checksum="$(cksum "$project/skills/project/release-policy/SKILL.md")"
assert_exit 0 run_cli "$project" init --force
after_checksum="$(cksum "$project/skills/project/release-policy/SKILL.md")"
assert_eq "$before_checksum" "$after_checksum" "project skill changed during force refresh"

test_start "reinitialization is idempotent"
assert_exit 0 run_cli "$project" init
assert_eq 1 "$(line_count ".cyberpunk/runs/" "$project/.gitignore")" "run ignore count"
assert_eq 1 "$(line_count ".worktrees/" "$project/.gitignore")" "worktree ignore count"

test_start "status is read-only"
status_before="$(git -C "$project" status --porcelain)"
assert_exit 0 run_cli "$project" status
status_after="$(git -C "$project" status --porcelain)"
assert_eq "$status_before" "$status_after" "status changed the project"

test_start "generated policy defines safe job integration"
policy="$(<"$project/.cyberpunk/config.yml")$(<"$project/.cyberpunk/workflow.md")"
for value in \
    "default: integration-branch" \
    "require_worktrees: true" \
    "allow_internal_commits: true" \
    "allow_protected_branch_merge: false" \
    "worker branch" \
    "Gatekeeper" \
    "dependency order" \
    "assembled verification" \
    "cleanup"; do
    assert_contains "$policy" "$value" "integration policy"
done

test_start "validate rejects unsafe protected-branch policy"
sed 's/allow_protected_branch_merge: false/allow_protected_branch_merge: true/' \
    "$project/.cyberpunk/config.yml" > "$project/.cyberpunk/config.yml.tmp"
mv "$project/.cyberpunk/config.yml.tmp" "$project/.cyberpunk/config.yml"
capture run_cli "$project" validate
assert_eq 1 "$COMMAND_STATUS"
assert_contains "$COMMAND_OUTPUT" "protected branch"

echo "PASS: integration tests"
